# Generated by Django 3.0.3 on 2020-02-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='test',
            field=models.CharField(default='plop', max_length=100),
            preserve_default=False,
        ),
    ]
